name: Auto reviewer
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
jobs:
  auto-reviewer:
    permissions: write-all
    name: Auto reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: necojackarc/auto-request-review@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers/reviewers.yml